function scrollToBottom() {
    var elem = document.getElementById('terminal');
    elem.scrollTop = elem.scrollHeight
}

var screen = document.getElementById('terminal');

var typeToScreen = new Typewriter(screen, {
    loop: false,
    delay: 1,
    autoStart: true,
    cursor: '█',
    strings: []
});

typeToScreen
    .deleteAll()
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('used connections closed<br>')
    .callFunction(scrollToBottom)
    .typeString('used memory freed<br>')
    .callFunction(scrollToBottom)
    .typeString('used temporary files removed<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom)
    .typeString('*          BUILD SUCCESSFULL             *<br>')
    .callFunction(scrollToBottom)
    .typeString('******************************************<br>')
    .callFunction(scrollToBottom);