name: Go

on:
  push:
    branches:
      -'*' 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for Linux/64
      run: env GOOS=linux GOARCH=amd64 go build -v -o release/oddlysatisfying ./...

    - name: Build for Windows/64
      run: env GOOS=windows GOARCH=amd64 go build -v -o release/oddlysatisfying.exe ./... 

    - name: Build for Darwin/64
      run: env GOOS=darwin GOARCH=amd64 go build -v -o release/oddlysatisfying.mac ./... 

    - name: Test
      run: release/oddlysatisfying
      