name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for Linux/64
      run: env GOOS=linux GOARCH=amd64 go build -v ./... -o oddlysatisfying

    - name: Build for Windows/64
      run: env GOOS=windows GOARCH=amd64 go build -v ./... -o oddlysatisfying.exe
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: oddlysatisfying
        path: ./oddlysatisfying*
